version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    EKS_CLUSTER_NAME: "k8s-voting-app"

phases:
  install:
    commands:
      - echo "Installing necessary tools"
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin
      - kubectl version --client
  pre_build:
    commands:
      - echo "Configuring kubectl with EKS cluster"
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
  build:
    commands:
      - echo "Deploying application to EKS"
      - kubectl apply -f k8s-specifications/db-secret.yaml
      - kubectl apply -f k8s-specifications/db-deployment.yaml
      - kubectl apply -f k8s-specifications/db-service.yaml
      - kubectl apply -f k8s-specifications/redis-deployment.yaml
      - kubectl apply -f k8s-specifications/redis-service.yaml
      - kubectl apply -f k8s-specifications/worker-deployment.yaml
      - kubectl apply -f k8s-specifications/ingress-controller.yaml
      - sleep 15
      - kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission
      - kubectl apply -f k8s-specifications/vote-deployment.yaml
      - kubectl apply -f k8s-specifications/vote-service.yaml
      - kubectl apply -f k8s-specifications/result-deployment.yaml
      - kubectl apply -f k8s-specifications/result-service.yaml
      - kubectl apply -f k8s-specifications/app-ingress.yaml
  post_build:
    commands:
      - echo "Deployment complete"

artifacts:
  files:
    - "**/*"
  discard-paths: yes
